### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#1]
Hello there!!

- If you find any typo mistakes, grammatical error or you can improve the documentation much better then feel free to work on this issue. 
- You are free to use your own idea, just make changes and improve this repository documentation. 
- Remember create pull requests only after 1 October.

Happy Contribution👍

**Comment by Sambhav250703** [comment]
Hey @kishanrajput23 👋 👋
Can I contribute on this issue ? If yes please assigned it to me

**Comment by kishanrajput23** [comment]
Hii @Sambhav250703 
You don't need to be assigned on this issue. Just go ahead and make contribution.

**Comment by Sambhav250703** [comment]
> Hii @Sambhav250703 You don't need to be assigned on this issue. Just go ahead and make contribution.

Okkk 👍👍

**Comment by siddhesh3607** [comment]
Hey @kishanrajput23 👋 👋
Can I contribute on this issue ? If yes please assigned it to me

**Comment by kishanrajput23** [comment]
Hii @0xPratyush 
You don't need to be assigned on this issue. Just go ahead and make contribution

**Comment by Sameeksha7464** [comment]
Hey I want to contribute on this issue, can I contribute?
