### ISSUE TITLE
Must Read Before Contributing

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#2]
Hello there!!

Thanks for choosing my project for contribution. So, before you contribute there are few things you need understand and then start with your open source journey.

### Rules / Guidelines

1. You all are free to contribute anything in this project but, you have to do contribution in certain things which is only available or described in already created `Issues`.
2. If you find an issue that suits you then make changes as per the instructions given in particular issue.
3. After working on issue don't create multiple PR's, firstly wait for one PR get to merged then create new PR.
4. If I find anyone who's doing spamming in my issues then I'll directly block him/her without giving any prior information.
5. If you have any doubts then feel free to open an issue with suitable title name or you can use `Discussions` tab for discuss your doubts over there.
6. If you want to work on other things that is not available on my issues then please inform me via creating an issue and describe all the things related to your idea. 

Happy Contributions👍

**Comment by VISWANATH78** [comment]
ok

**Comment by Shubham2816** [comment]
can u assign me share blog for pull request

**Comment by VISWANATH78** [comment]
Sure

**Comment by amaan0810** [comment]
can you assign me share blog for pull request please

**Comment by VISWANATH78** [comment]
sure mate goahead!
