### ISSUE TITLE
CSS Animations

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#21]
Hello there!!

In this task you just have to create a css animation of your choice.

### Instructions
- Firstly make another branch and you can name it as per your choice. Remember don't make changes directly in `main` branch.
- Inside `CSS Animations` folder create a new folder and name it as `your-github-username`. For example `kishanrajput23`.
- Inside `your-github-username` folder add all the source code and add `README.md` file also.
- Inside your README.md file, add the screenshots of your working project and if possible add your css animation deployed link. 
- Now commit the changes, push them and create new PR. 
- Now wait for your PR to get merged. 

### Tip : Complete this process in Github (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your valuable contribution. 👍

**Comment by amanfangeria980** [comment]
Hey, I want to try this issue, can you assign this to me it's my first time contributing to open-source.

**Comment by abitsalihu** [comment]
Hey @kishanrajput23, I would like to do this, do we need to be assigned or can we just fork it and send the PR without  being assigned?

**Comment by flow6979** [comment]
hey @kishanrajput23, I am very much interested in contributing to this repository. It would be great if you assign this to me.
Thank you.

**Comment by dishant-yadav** [comment]
Hey @kishanrajput23, I would like to **contribute** to this issue. Can you please **assign** this issue to me?
I can start working on the issue as soon as you assign it.

**Comment by kishanrajput23** [comment]
Hello @dishant-yadav @abitsalihu @flow6979 @amanfangeria980 
Go ahead guys :rocket: 
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by Anikaaasingh** [comment]
Hey @kishanrajput23 I would like to contribute for the same. Can I do it?

**Comment by kishanrajput23** [comment]
Go for it @Anikaaasingh :rocket:

**Comment by Anikaaasingh** [comment]
Will it be considered as a contribution in Hacktoberfest 2022 if I create a PR rn?

**Comment by kishanrajput23** [comment]
Yes @Anikaaasingh

**Comment by abitsalihu** [comment]
@kishanrajput23 should it be purely `css` or can I add a bit of `vanilla JS` to make it more interesting. :)

**Comment by kishanrajput23** [comment]
@abitsalihu yes you can :+1:

**Comment by adi-uchiha** [comment]
Hey I can make interactive css svg animations. Please assign me

**Comment by kishanrajput23** [comment]
Go ahead @adi-uchiha

**Comment by kishanrajput23** [comment]
Go for it @Ukesh-dev 👍
