### ISSUE TITLE
I want to add css animation

### ISSUE THREAD

**Issue by abhishektyagi2912** [kishanrajput23/Hacktoberfest-2022#231]

**Comment by abhishektyagi2912** [comment]
plz assign me this task under hackoctober fest

**Comment by Sam10-debug** [comment]
alright
i would like to be assigned this task

**Comment by BhupeshXD** [comment]
i would like to contribute can you assign me for this

**Comment by PurtiMishra** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by harshneolia** [comment]
Assign This Task To me sir...I can Easily Do it in a Beautiful Way
