### ISSUE TITLE
Want to make the weatherapp

### ISSUE THREAD

**Issue by psai0011** [kishanrajput23/Hacktoberfest-2022#272]
feature : landing page of project is weatherapp
Assign the issue to me @kishanrajput23

**Comment by PurtiMishra** [comment]
Hello Sir! I request you to kindly assign this task to me.

**Comment by arnav-vivian** [comment]
hello sir, could you please assing me this. This is my first hacktoberfest participation.

**Comment by trivedi2u** [comment]
plz assign me this issue
