### ISSUE TITLE
Basic Portfolios

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#3]
In this particular task you have to just create your portfolio and then add it into this project. Sounds simple!!!

#### Instructions
1. Firstly create a new folder and name it as `Basic Portfolios`. Remember create this folder only if it's not present in main branch.
2. Under `Basic Portfolios` create a new folder of  `your_github_username`
3. Under `your_github_username` folder add your all source codes and don't forget to add `README.md` file in it.
4. Now open your `README.md` file and add the details given below"
```
Name : Your Name
School/College : Name of your school/college
GitHub Username : Your Username
GitHub Profile URL : Your GitHub Profile URL
Tech Stack : Mention tech stack you used while building your portfolio. Example : HTML, CSS, JS, etc.
```
5. Lastly add screenshots of your portfolio in `README.md` file.
6. Now commit the changes and push it.
7. Now create a `Pull Request` and wait for get verified.

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you so much for your valuable contribution.☺

**Comment by Sambhav250703** [comment]
Hey @kishanrajput23 👋 👋 
Can I contribute on this issue ?
If yes please assigned it to me

**Comment by sreejasaha19** [comment]
Can I contribute on this issue ?If yes please assigned it to me

**Comment by manmohan4142** [comment]
Hey @kishanrajput23  Can I contribute on this issue ?
If yes please assigned it to me.

**Comment by Harshit1020** [comment]
Can I contribute on this issue ?If yes please assigned it to me

**Comment by Ank-1234** [comment]
Hello, I would like to work on this issue.

**Comment by Dhanshriborse** [comment]
Hey! I would love to work on this. please assign it to me.

**Comment by kishanrajput23** [comment]
Hii @Ank-1234 and @Dhanshriborse 

You both are good to go 🚀 
No need to assigning an issue you can start working on it because this issue will never close.

**Comment by Anas9764** [comment]
hey @kishanrajput23  
I happy if you give me chance for contribute on this issue.
 please assign it to me

**Comment by kishanrajput23** [comment]
Hello @crg46306 @Anas9764 
Go ahead guys :rocket: 
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by flow6979** [comment]
hey @kishanrajput23, i want to add my contribution to this repository.; can you please assign this to me so that I can create and add my portfolio here?

**Comment by kishanrajput23** [comment]
Go ahead @flow6979 
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by jyotirmaya907** [comment]
I want add my portfolio also.Can i do that ? please assign to me.

**Comment by kishanrajput23** [comment]
Go ahead @jyotirmaya907

**Comment by Anikalp1** [comment]
@kishanrajput23, I will be contributing for this issue.

**Comment by AbhishekTiwari23** [comment]
@kishanrajput23, sir, can you please give me a chance to work on this project

**Comment by tussharpaul13** [comment]
sir give me chance to work on it.. Please assign me !!

**Comment by kishanrajput23** [comment]
Go ahead guys @Anikalp1 & @AbhishekTiwari23 👍

**Comment by dishant-yadav** [comment]
@kishanrajput23
Can you please give me a chance to work on this issue?

**Comment by itsmnsi** [comment]
@kishanrajput23 
I want to contribute my portfolio. Can you please give me a chance to work on this issue?

**Comment by imyoungsparda** [comment]
is this repository in a Hackctoberfest?

**Comment by qasim0014** [comment]
Can I still contribute?

**Comment by minhaj-313** [comment]
I want to Contribute in this Project for Hacktoberfest, If you Have any Issue then you can suggest me. I want to give my best, Thanks
