### ISSUE TITLE
Create GUI Games

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#32]
Hello there!!

In this task you just have to create a GUI Games of your choice and it can be in any language.

### Instructions
- Firstly make another branch and you can name it as per your choice. Remember don't make changes directly in `main` branch.
- Inside `GUI Games` folder create a new folder and name it as `your-github-username`. For example `kishanrajput23`.
- Inside `your-github-username` folder add all the source code and add `README.md` file also.
- Inside your README.md file, add the screenshots of your working project and if possible add your project deployed link. 
- Now commit the changes, push them and create new PR. 
- Now wait for your PR to get merged. 

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your valuable contribution. 👍

**Comment by dishant-yadav** [comment]
@kishanrajput23 
Can you please assign me this issue?
I would like to create a **Rock, Paper and Scissor** game in JS.

**Comment by kishanrajput23** [comment]
Go ahead @dishant-yadav :rocket:

**Comment by harsh1x4** [comment]
Hello @kishanrajput23 Sir, Can I simply write a Java programme that, when run, can be used through the console?

**Comment by kishanrajput23** [comment]
Hii @harsh1x4 
You can only work on the issues which is mentioned in this repository

**Comment by Prajwal0225** [comment]
Hello 👋🏽, @kishanrajput23. I'd like to contribute my dice game to this repository.

Here is the live link: `https://prajwal0225.github.io/Dice-Game/`

**Comment by AbhishekTiwari23** [comment]
I want to add a snake game, and please give it a chance.

**Comment by kishanrajput23** [comment]
Go ahead @Prajwal0225 and @AbhishekTiwari23

**Comment by Aman0786-git** [comment]
Can you please assign me this
