### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#4]
Let's create our childhood game once again!! 😅

### Instructions
- Create a folder and name it as `Tic Tac Toe`. Create this folder only if it's not available. 
- Inside `Tic Tac Toe` folder create a new folder and name it as `your-github-username`.
- Inside `your-github-username` folder add all the source code and add `README.md` file also. 
- Inside your `README.md` file, add the screenshots of your working project. 
- Now the most important thing, if this game is already available in one language then please don't create this project in again same language. Either you can create this project in other language or you can modify/make changes in already available project. 
- Now commit the changes, push them and create new PR. 
- Now wait for your PR to get merged. 

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your valuable contribution. 👍

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by manav-06** [comment]
Hi @kishanrajput23 I would like to work on this

**Comment by Nandinisaagar** [comment]
Hey!
I would like to contribute in this project, please assign it to me.

**Comment by vikash485** [comment]
Hello @kishanrajput23, I would like to contribute to this project, please assign it to me.

**Comment by AayushBiswas** [comment]
I would like to work on this project

**Comment by kishanrajput23** [comment]
Hii @codegoggins 

If you have some experience in coding then it is absolutely fine for yourself, just follow the instruction given above and create file according then add your code simple. If you want any other suggestion then feel free to comment.

**Comment by Anuran12** [comment]
hi @kishanrajput23 this is my first time contribution . please assign it to me

**Comment by Anuran12** [comment]
hi , I am your subscriber. can you please make a video on how can I do pull requests.

**Comment by kishanrajput23** [comment]
Hii @Anuran12 
The video will be live at 7 PM today on my channel.

**Comment by AayushBiswas** [comment]
Will I do it online or players can play from one mobile or bot

**Comment by kishanrajput23** [comment]
Hii @AayushBiswas 
You are free to implement your ideas. So, implement the one which you think is most suitable.

**Comment by codegoggins** [comment]
@kishanrajput23 I have implemented the game . What should I do next ??
I am also participating in Hacktoberfest . So could you please guide accordingly.

**Comment by kishanrajput23** [comment]
@codegoggins now just make pull request for reference you can watch any youtube video

**Comment by codegoggins** [comment]
How do I add screenshots of my project in README.md file that I have created in my folder

**Comment by kishanrajput23** [comment]
@codegoggins You have give url of your cloned repository. When you click on `Code` button you'll get an url copy that then clone it.

**Comment by error707-persona** [comment]
Hey, I would like to work on this. Can you assign it to me?

**Comment by crg46306** [comment]
Hey!
I would like to contribute in this project, can you please assign it to me?

**Comment by kishanrajput23** [comment]
Hello @crg46306 @just-injoey @error707-persona 
Go ahead guys :rocket: 
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by dishant-yadav** [comment]
Hey there!
I would like to contribute in this issue, can you please assign it to me?

**Comment by Ep1c-paav** [comment]
hey @kishanrajput23 
i would like to contribute in this issue.

**Comment by kishanrajput23** [comment]
Hello @Ep1c-paav and @dishant-yadav 
Go ahead guys rocket
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by vedant-z** [comment]
@kishanrajput23 I want to work on this

**Comment by PrateekDey** [comment]
@kishanrajput23 Hi, I would like to contribute to this issue. Please assign it to me also.

**Comment by adi-uchiha** [comment]
I like to contribute to this issue. Please Assign me

**Comment by tussharpaul13** [comment]
i Like to contribute on it please assign me !!

**Comment by AbhishekTiwari23** [comment]
I like to contribute to it, and please give me a chance to express my efforts

**Comment by kishanrajput23** [comment]
Go for it @AbhishekTiwari23 @adi-uchiha @vedant-z @PrateekDey

**Comment by RockingRishav** [comment]
Hey @kishanrajput23  I wanted to add TicTacToe in Kotlin(Android) but this issue is now closed could you tell how can i contribute now?

**Comment by error707-persona** [comment]
!assign
