### ISSUE TITLE
Convert this project into a webpage

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#5]
Hello there!!

I just want to convert this repo into a fully functional webpage which has below functionalities:

- It should be responsive
- Pretty user interface as per your interest
- It should be able to add new contributors
- it should contain a search bar where any contributors can find himself/herself
- For example : 

![image](https://user-images.githubusercontent.com/70385488/192354508-f606af9d-fca0-4f45-94cf-d70dc3bef1fa.png)

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your contribution. 👍

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by manav-06** [comment]
Hi @kishanrajput23 this seems interesting. You can assign this to me

**Comment by BinniesLite** [comment]
Hi @kishanrajput23 I would like to assist on this too!

**Comment by adi-uchiha** [comment]
I am interested on working on this project. Can you assign this to me

**Comment by Preethi-Dev** [comment]
Hi @kishanrajput23, I'm working on modern designs. This project Seems fascinating and most reasonable for contributors. I feel gleeful to work on this project. Can you please assign it to me?

**Comment by AbhishekTiwari23** [comment]
Want to contribute to it, please give me a chance.

**Comment by kishanrajput23** [comment]
Go ahead everyone, I'll give fare chance to everyone

@AbhishekTiwari23 @Preethi-Dev @ritish1082 @adi-uchiha
