### ISSUE TITLE
Cloned Projects

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#6]
In this task you have to just clone anything and contribute in this project. For example you can make clone of netflix, facebook, instagram, etc and remember it should be responsive.

### Instructions
- Create a folder and name it as `Cloned  Projects`. Create this folder only if it's not available. 
- Inside `Cloned Projects` folder create a new folder and name it as `your-github-username_your-cloned-project-name` for example `kishanrajput23_Netflix_Clone`.
- Inside `your-github-username_your-cloned-project-name` folder add all the source code and add `README.md` file also. 
- Inside your `README.md` file, add the screenshots of your working project. 
- Now the most important thing, if any clone is already available in this folder then please don't create this project again.
- Now commit the changes, push them and create new PR. 
- Now wait for your PR to get merged. 

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your valuable contribution. 👍

**Comment by Nandinisaagar** [comment]
Hey!
I would like to contribute in this project, please assign it to me.

**Comment by akashdnb** [comment]
Hey!
I would like to contribute in this project, please assign it to me.

**Comment by maharshi-sinha** [comment]
Hey, Would like to contribute to this

**Comment by kishanrajput23** [comment]
Go ahead  @maharshi-sinha 🚀

**Comment by ashu2206** [comment]
Hey!
I would like to contribute in this project, please assign it to me.

**Comment by maharshi-sinha** [comment]
Hey I want to contribute into this project again! can you assign it to me
