### ISSUE TITLE
BMI CLI Tool

### ISSUE THREAD

**Issue by semihberkayozturk** [kishanrajput23/Hacktoberfest-2022#68]
I want to make a CLI tool for BMI calculations. Can you assign this issue to me?

**Comment by kishanrajput23** [comment]
Can you please work on already created issues because in hacktoberfest issue s doesn't play any vital role if it's big open source project. I'll consider your idea don't worry about that but, let me create an issue related to CLI Tool so that rest of the people can also contribute.

**Comment by semihberkayozturk** [comment]
@kishanrajput23  okay that's sounds good, do you want me to close this issue?
