### ISSUE TITLE
Share your blogs

### ISSUE THREAD

**Issue by kishanrajput23** [kishanrajput23/Hacktoberfest-2022#8]
Hello there!!

In this task you just have to write a blog on any topic of your choice. You can also share your previously written blogs. This task is especially for Non-Coders.

### Instructions
- Create a folder and name it as `Blogs`. Create this folder only if it's not available. 
- Inside `Blogs` folder create a new file and name it as `your-github-username.md` for example `kishanrajput23.md`.
- Inside `your-github-username.md` file write your content with proper use of markdown and add images if it's require because it will help others to understand better.
- Now commit the changes, push them and create new PR. 
- Now wait for your PR to get merged. 

### Tip : Complete this process in GitHub (in your browser)

```mermaid
flowchart LR
    Fork[Fork the project]-->branch[Create a New Branch]
    branch-->Edit[Edit file]
    Edit-->commit[Commit the changes]
    commit -->|Finally|creatpr((Create a Pull Request))
    
 ```

Thank you for your valuable contribution. 👍

**Comment by 0xPratyush** [comment]
Hello, I would like to work on this issue.. assign if possible :)

**Comment by manav-06** [comment]
Hi. You can assign this to me

**Comment by RadhikaChhabra17** [comment]
Hello, I would like to work on this issue. Can you assign this to me?

**Comment by Girlwithasmile** [comment]
Hey, I am a hackthoberfest contributer. Can u assign this to me?

**Comment by kishanrajput23** [comment]
Hii @RadhikaChhabra17 and @Girlwithasmile you both are good to go 🚀

Pleased make changes as per the instructions and assigning issue is not mandatory.

**Comment by RohitRajvaidya5** [comment]
Hello, I would like to work on this issue. Can you assign this to me?

**Comment by Akshatpattiwar512** [comment]
I would like to contribute in this issue.

**Comment by crg46306** [comment]
Hello. I would like to work on this issue . can you assign this to me ?

**Comment by kishanrajput23** [comment]
Hello @Akshatpattiwar512 @crg46306 @RohitRajvaidya5 
Go ahead guys :rocket: 
You don't need to be assigned on any issues in Hacktoberfest.

**Comment by jyotirmaya907** [comment]
I want to contribute to this issue.Can u assign to me ?

**Comment by kishanrajput23** [comment]
Go for it @jyotirmaya907

**Comment by RohitRajvaidya5** [comment]
Done!!!

**Comment by stenwire** [comment]
Please is this issue open, I would like to be assigned.
