### ISSUE TITLE
CSS animation 

### ISSUE THREAD

**Issue by ankushrai999** [kishanrajput23/Hacktoberfest-2022#88]
You must tell something about css animations in your readme like
An animation lets an element gradually change from one style to another.

You can change as many CSS properties you want, as many times as you want.

To use CSS animation, you must first specify some keyframes for the animation.

Keyframes hold what styles the element will have at certain times.

**Comment by ankushrai999** [comment]
You write something

**Comment by iamrishabhjoshi** [comment]
Please assign this issue this to me @ankushrai999
